### ISSUE TITLE
Ipss core lib could be outdated

### ISSUE THREAD

**Issue by thuang** [InterPSS-Project/ipss-common#13]
@jinjingfarm I had the following error when switching from source codes (development mode) to ipss core lib. 

![Ipss_core_lib](https://user-images.githubusercontent.com/529196/72865992-a802cd80-3c8e-11ea-8cea-21f391a4d392.png)

**Comment by jinjingfarm** [comment]
@thuang the issue should be resolved with the InterPSS lib update.

**Comment by thuang** [comment]
The problem has been solved.
