### ISSUE TITLE
Unable to log in to the homepage of InterPSS Community.

### ISSUE THREAD

**Issue by roki1031** [InterPSS-Project/ipss-common#18]
hello, im a student from chinese. I want to learn how to use InterPSS, but I can't log in to the community homepage (the proxy has been opened). Does interPSS have other login methods in China?

**Comment by jinjingfarm** [comment]
Thank you for bringing up the issue. Currently, the best approach to learn InterPSS is by reading the following tutorial:

https://github.com/InterPSS-Project/ipss-common/blob/master/ipss.tutorial/docs/InterPSS%20Application%20and%20Development%20tutorial.pdf
