### ISSUE TITLE
com.interpss.core.aclf.impl.AclfLoadImpl class not included in the core lib?

### ISSUE THREAD

**Issue by thuang** [InterPSS-Project/ipss-common#6]
When I build the ipss.plugin.multinet project using the core libs, there is an error: 

Description Resource    Path    Location    Type
The type com.interpss.core.aclf.impl.AclfLoadImpl cannot be resolved. It is indirectly referenced from required .class files    TestTnD_IEEE9_8BusFeeder.java   /ipss.plugin.multiNet/src/org/ipss/multiNet/test/trans_dist line 1  Java Problem

**Comment by jinjingfarm** [comment]
The lib has been rebuilt, please sync with commit https://github.com/InterPSS-Project/ipss-common/commit/97d021d690360e347f26fef889a4c5a531add232.
